# Generated by Django 2.2 on 2019-04-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='descriptiion',
            new_name='description',
        ),
    ]
